version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: node --version
       
